# Ex. 0 | **Levendis**
### GEC0319 | JIVB | Time Series


## <span style='font-family:sans-serif'>  📚 Contents

1. [**I Introduction**](#I)
2. [**II ARMA Process**](#II)
3. [**III Model Selection in ARMA(p,q) Processes**](#III)
4. [**IV Stationarity and Invertibility**](#IV)
5. [**V Non-stationarity and ARIMA(p,d,q) Processes**](#V)
6. [**VI Seasonal ARMA(p,q) Processes**](#VI)
7. [**VII Unit Root Tests**](#VII)
8. [**VIII Structural Breaks**](#VIII)
9. [**IX ARCH, GARCH and Time-Varying Variance**](#IX)
10. [**X Vector Autoregressions I: Basics**](#X)
11. [**XI Vector Autoregressions II: Extensions**](#XI)
12. [**XII  Cointegration and VECMs**](#XII)
    
</span>

## Settings

In [1]:
# !pip install yfinance --upgrade --no-cache-dir
import os
import numpy as np
import pandas as pd
import yfinance as yf

import matplotlib.pyplot as plt
from statsmodels.tsa.stattools import acf, kpss
from statsmodels.formula.api import ols

## Get Data

In [2]:
! git clone https://github.com/jlevendi/Time-Series-Econometrics.git

Cloning into 'Time-Series-Econometrics'...
remote: Enumerating objects: 124, done.
remote: Counting objects: 100% (22/22), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 124 (delta 3), reused 0 (delta 0), pack-reused 102 (from 1)
Receiving objects: 100% (124/124), 6.84 MiB | 21.95 MiB/s, done.
Resolving deltas: 100% (8/8), done.

In [3]:
path = '/content/Time-Series-Econometrics/book data for distribution/stata_data'
files = os.listdir(path)
files[0:10]

['AR1nonzero_b.dta',
 'Hausman_HW_3.dta',
 'PanelUnitRoot.dta',
 'xtGDPlong.dta',
 'realexchangerates7398.csv',
 'xtcoint.dta',
 'stationarity_ex.dta',
 'DTdata.dta',
 'realexchangerates7398.dta',
 'ARMAexamples.dta']

In [5]:
datos = pd.read_stata(os.path.join(path,files[0]))
datos.head(3)

    time     error          X
0  901.0  1.513708  20.861327
1  902.0  1.137759  21.568423
2  903.0 -0.153930  20.630281

## Practice

# I
---

1.6 Exercises
1. Given the time series: X = [2, 4, 6, 8, 10], where X1 = 2, X2 = 4,. . . , and
X5 = 10, calculate, by hand, the first and second lags of X. Also calculate the
first and second differences of X.
2. Given the time series: X = [10, 15, 23, 20, 19], where X1 = 10, X2 =
15,. . . calculate, by hand, the first and second lags, and the first and second
differences of X.
3. Enter into Stata the following time series: X = [10, 15, 23, 20, 19]. Create a
time variable (with values 1 through 5) and tell Stata that these are a time series
(tsset time). Using Stata, calculate the first and second lags, and the first
and second differences of X.
4. Download the daily adjusted closing price of IBM stock from 1990–2012 using
fetchyahooquotes. Take the natural logarithm of this price. Then, using
Stata’s D notation, generate a new variable containing the percentage returns of IBM’s share price. (The first difference of the logs is equal to the percentage
change.) What is the average daily rate of return for IBM during this period?
On which date did IBM have its highest percentage returns? On which date did
it have its lowest percentage returns?
5. Download the daily adjusted closing price of MSFT stock from 2000–2012
using fetchyahooquotes. Take the natural logarithm of this price. Then,
using Stata’s D notation, generate a new variable containing the percentage
returns of Microsoft’s share price. (The first difference of the logs is equal to
the percentage change.) What is the average daily rate of return for Microsoft
during this period? On which date did Microsoft have its highest percentage
returns? On which date did it have its lowest percentage returns?
6. Suppose midterm grades were distributed normally, with a mean of 70 and a
standard deviation of 10. Suppose further that the professor multiplies each
exam by 1.10 as a curve. Calculate the new mean, standard deviation, and
variance of the curved midterm grades.
7. Suppose X is distributed normally with a mean of 5 and a standard deviation
of 2. What is the expected value of 10X? What is the expected value of 20X?
What are the variance and standard deviations of 5X and of 10X?
8. Suppose that two exams (the midterm and the final) usually have averages of
70 and 80, respectively. They have standard deviations of 10 and 7, and their
correlation is 0.80. What is their covariance? Suppose that the exams were not
weighted equally. Rather, in calculating the course grade, the midterm carries a
weight of 40% and the final has a weight of 60%. What is the expected grade for
the course? What is the variance and standard deviation for the course grade?
9. Suppose that an exam has an average grade of 75 and a standard deviation of
10. Suppose that the professor decided to curve the exams by adding five points
to everyone’s score. What are the mean, standard deviation and variance of the
curved exam?
10. Suppose that in country A, the price of a widget has a mean of $100 and a
variance of $25. Country B has a fixed exchange rate with A, so that it takes
two B-dollars to equal one A-dollar. What is the expected price of a widget in
B-dollars? What is its variance in B-dollars? What would the expected price
and variance equal if the exchange rate were three-to-one?

In [6]:
# 1
def get_lag(lista,lag):
    return  lista[lag:] + [np.nan for i in range(lag)]

# Given time series
X = [2, 4, 6, 8, 10]

# Calculate first and second lags
first_lag = get_lag(X,1)
second_lag = get_lag(X,2)

# Display the results
print("Original Series:", X)
print("First Lag:", first_lag)
print("Second Lag:", second_lag)

Original Series: [2, 4, 6, 8, 10]
First Lag: [4, 6, 8, 10, nan]
Second Lag: [6, 8, 10, nan, nan]

In [7]:
def get_diff(X, n=1):
    diffs = np.diff(X, n=n)
    return np.concatenate([ np.full(n, np.nan), diffs])

# Calculate first and second differences
first_difference = get_diff(X,1)
second_difference = get_diff(X, n=2)

print("First Difference:", first_difference)
print("Second Difference:", second_difference)

First Difference: [nan  2.  2.  2.  2.]
Second Difference: [nan nan  0.  0.  0.]

In [ ]:
# Create a DataFrame
df = pd.DataFrame({'X':X,'first_lag':first_lag,'second_lag':second_lag,'first_difference':first_difference,'second_difference':second_difference})
df

    X  first_lag  second_lag  first_difference  second_difference
0   2        4.0         6.0               NaN                NaN
1   4        6.0         8.0               2.0                NaN
2   6        8.0        10.0               2.0                0.0
3   8       10.0         NaN               2.0                0.0
4  10        NaN         NaN               2.0                0.0

In [ ]:
# 4
obj = yf.Ticker('ibm')
data = obj.history(period="max")
data.reset_index(inplace=True)
data.head(5)

,Date,Open,High,Low,Close,Volume,Dividends,Stock Splits
0,1962-01-02 00:00:00-05:00,1.559231,1.559231,1.541711,1.541711,407940,0.0,0.0
1,1962-01-03 00:00:00-05:00,1.541710,1.555187,1.541710,1.555187,305955,0.0,0.0
2,1962-01-04 00:00:00-05:00,1.555186,1.555186,1.539014,1.539688,274575,0.0,0.0
3,1962-01-05 00:00:00-05:00,1.537668,1.537668,1.506672,1.509367,384405,0.0,0.0
4,1962-01-08 00:00:00-05:00,1.508018,1.508018,1.468937,1.481065,572685,0.0,0.0

In [ ]:
df = data[(data['Date'].dt.year > 1990) & (data['Date'].dt.year < 2012)]
df.set_index('Date',inplace=True)
df.head()

,Open,High,Low,Close,Volume,Dividends,Stock Splits
Date,,,,,,,
1991-01-02 00:00:00-05:00,12.112475,12.206369,12.031993,12.031993,4341737,0.0,0.0
1991-01-03 00:00:00-05:00,12.058819,12.219782,12.045405,12.072232,5470162,0.0,0.0
1991-01-04 00:00:00-05:00,12.099061,12.125889,12.005167,12.031993,4540058,0.0,0.0
1991-01-07 00:00:00-05:00,11.951514,12.005169,11.803964,11.830791,4976450,0.0,0.0
1991-01-08 00:00:00-05:00,11.844203,11.844203,11.669826,11.696652,7177652,0.0,0.0

# II
---
2.1 Exercise
1. Using the definitions in Eqs. (2.3) and (2.4), show whether the purely random
process
Xt = β0 + et with et ∼ iidN (0, 1)
is mean stationary, variance stationary, and covariance stationary.

2.3.1 Exercises
Let’s practice estimating AR(p) models using the dataset ARexamples.dta. The
dataset consists of a three variables (X, Y and Z) and a time variable.
1. What is equation of the AR(p) process corresponding to the following Stata
estimation commands?
(a) arima X, ar(1/4) nocons
(b) arima X, ar(1 2 4) nocons
(c) arima X, ar(2 4) nocons
2. Write out the arima estimation command you would use to estimate the
following AR processes:
(a) Xt = β1Xt−1 + β2Xt−2 + β3Xt−3 + β4Xt−4 + et
(b) Xt = β1Xt−1 + β2Xt−2 + β3Xt−3 + et
(c) Xt = β1Xt−1 + β4Xt−4 + et
3. Using the ARexamples.dta dataset, graph the last 100 observations of X over
time. Using all of the observations, estimate the AR(1) model,
Xt = β1Xt−1 + et .
Verify that the coefficient is approximately: βˆ
1 ≈ 0.50.
4. Using the ARexamples.dta dataset, graph the last 100 observations of Y over
time. Using all of the observations, estimate the AR(2) model,
Yt = β1Yt−1 + β2Yt−2 + et .
Verify that the coefficients are approximately: βˆ
1 ≈ 0.70 and βˆ
2 ≈ 0.20.
5. Using the ARexamples.dta dataset, graph the last 100 observations of Z over
time. Using all of the observations, estimate the AR(3) model,
28 2 ARMA(p,q) Processes
Zt = β1Zt−1 + β2Zt−2 + β3Zt−3 + et .
Verify that the coefficients are approximately: βˆ
1 ≈ 0.60, βˆ
2 ≈ 0.20, and βˆ
3 ≈
0.10.
6. Using the ARexamples.dta dataset, estimate the AR(3) model,
Zt = β1Zt−1 + β3Zt−3 + et .
Notice that this is a restricted model, where the coefficient on the second lag is
set to zero. Verify that the estimated coefficients are approximately: βˆ
1 ≈ 0.70,
and βˆ
3 ≈ 0.20.

# III
---

3.1.1 Exercises
1. Using Eqs. (3.26)–(3.30), calculate the first three lags of the theoretical ACFs
implied by the following AR(2) processes:
(a) Xt = 0.50Xt−1 − 0.20Xt−2 + et
(b) Xt = −0.50Xt−1 − 0.20Xt−2 + et

3.1.2 Exercises
1. Use the formulas for the ACFs of an MA(3) processes derived above (i.e. (3.55)
through (3.58)) to calculate the first five values of the ACF of the following
processes:
(a) Xt = ut + 0.50ut−1 − 0.10ut−2 + 0.05ut−3.
(b) Xt = ut − 0.50ut−1 + 0.20ut−2 + 0.10ut−3.



3.2.2 Exercises
1. Using ARexamples.dta calculate the Empirical PACFs (out to five lags) for
variable Z using the regression approach. Do the same using corrgram. Verify
that your answers are the same regardless of which approach you use.
2. Using MAexamples.dta calculate the Empirical PACFs (out to five lags) for
variables X, Y and Z using the regression approach and using corrgram. Verify
that your answers are the same regardless of which approach you use.


3.3 Exercises
1. Load the dataset ARMAexercises.dta. Using the ac and pac commands
in Stata, calculate the Empirical ACF and PACF for each of the variables in the
dataset. What type of process seems to have generated each variable?
2. For each of the variables in the question above, estimate the AR, MA, or
ARMA model that seems to have generated the variable. Write out the estimated
3.4 Information Criteria 77
equation of each model. Pay special attention to whether the estimated constant
is statistically significant. If it is not, drop the constant from the model and reestimate.
3. Download data from FRED on the seasonally adjusted growth rate of nominal
GDP. (This is series: A191RP1Q027SBEA.) Use data from 1947 Q2 through
2017 Q2. Calculate its Empirical ACF and PACF. What type of ARMA(p,q)
process seems to best fit the ACF/PACF? Explain your reasoning. Estimate the
ARMA process and report your results. If necessary, modify your model based
on this output. Use your final estimated model to forecast out to five additional
periods. Graph your results. Compare your forecasted GDP numbers with the
real ones from FRED. Do you think your estimates are fairly good or not?

# IV
---
4.1 Exercises
1. Which of the following processes are stationary? Why? Express your answer in
terms of the Stralkowski Triangle inequalities.
(a) Xt = 1.05Xt−1 + et
(b) Xt = 0.60Xt−1 + 0.10Xt−2 + et
(c) Xt = 0.50Xt−1 + 0.30Xt−2 + et
(d) Xt = 0.80Xt−1 − 0.10Xt−2 + et

4.2 Exercises
1. For each of the remaining variables (Z, W, A, B, C and D) in the
stationarity_ex.dta dataset, answer the following:
(a) Estimate a zero-mean AR(2) model using Stata’s arima command.
(b) Check for stationarity using Stata’s estat aroots post-estimation command.
(c) Check for stationarity by using the quadratic formula to compute the roots of
the characteristic equation.
(d) Check for stationarity by using the quadratic formula to compute the roots of
the inverse characteristic equation.
(e) Which variables are not stationary?
(f) Do any of the variables seem to have roots on the unit circle (i.e. do they have
“unit roots?”)
Stata sometimes has problems estimating non-stationary ARIMA models. If it
cannot find an estimate, this is one indication that the estimated model is not
stationary. Still, if you want to force Stata into providing an estimate, you can try
using the diffuse option at the end of the arima command. The diffuse
estimates are suspect, though, so use this option sparingly. This will be necessary,
however, for some of the exercises above.

4.3 Exercises
1. For each of the following AR(2) process,
(a) Xt = 0.50Xt−1 + 0.10Xt−2 + et
(b) Xt = −0.50Xt−1 + 0.20Xt−2 + et
(c) Xt = 1.10Xt−1 + 0.20Xt−2 + et
Write down the characteristic equation and use the quadratic formula to find its
roots. Write down the inverse characteristic equation. Use the quadratic formula
to find its roots. Show that the two roots are reciprocals of each other.
2. For the following general AR(2) process,
Xt = β1Xt−1 + β2Xt−2 + et
Write down the characteristic equation; plug in the appropriate β’s into the
quadratic formula to describe its roots. Write down the inverse characteristic
equation; plug in the appropriate β’s into the quadratic formula to describe its
roots. Show that the two roots are reciprocals of each other. (Hint: Reciprocals
multiply to one.)

# V
---

5.4 Exercises
1. For each of the items listed below, you should be able to do the following:
Download the data, and calculate the first and second differences. Graph the
original series and the two differenced series. Visually identify its possible order
of integration.
(a) The nominal US GDP per capita. The command to download the data into
Stata is:
wbopendata, country(usa) indicator(ny.gdp.pcap.cd)
year(1960:2015) long clear.
(b) US CPI. The command to download the data into Stata is:
wbopendata , country(usa) indicator(fp.cpi.totl)
year(1960:2015) long clear.
2. The dataset integrated012.dta contains two sets of three variables: (A, B,
C) and (X, Y, Z). For each set, graph each variable. Calculate first and second
differences of each variable. Identify which variable is I(2), I(1), and I(0).

5.5 Exercises
1. Redo the exercise above, slowly increasing the sample size from 100, to 1000,
10,000 and 100,000. Summarize your results. Especially important, what are the
standard deviations? What conclusions do you draw?


5.6 Exercises
1. Use Stata to generate 1000 observations of a variable X, equal to random noise
from a normal distribution with zero mean and a standard deviation of two.
(a) Summarize X and verify that the mean is approximately zero and the variance
is four (since it is the square of the standard deviation).
(b) Use corrgram X, lags(5) to calculate the ACF and PACF of X out to
five lags. Verify that this is white noise with no autocorrelation structure.
(c) Summarize D1.X, the first difference of the variable. What is the mean? What
is its variance? Did it increase or decrease? In what way? Is this what you
expected?
(d) Use corrgram D1.X, lags(5) to calculate the ACF and PACF of the
first difference of X out to five lags. Describe its autocorrelation structure. Is
it positive or negative?
(e) Estimate an MA(1) model on D1.X using arima D1.X, ma(1).
(f) Use estat aroots to test graphically whether we have an MA unit root
in D1.X.

5.7 REPLICATING GRANGER & NEWBOLD 1974

# VI
---
Exercises
1. Generate 1000 observations from the model in Eq. (6.4), with β1 = 0.10,
β12 = 0.40, and β24 = 40. Graph the last 200 observations. Does the data
appear seasonal? Examine the autocorrelation structure of the data. Can you
detect seasonality?
2. What are the seasonal and non-seasonal AR and MA polynomials implied by
the following models? Multiply out these polynomials and write out the explicit
ARIMA model.
(a) ARIMA(1, 0, 1) × (1, 0, 0)12
(b) ARIMA(2, 0, 0) × (0, 0, 1)4
(c) ARIMA(0, 0, 1) × (0, 0, 2)12
(d) ARIMA(0, 0, 2) × (1, 0, 1)4
3. For each of the models listed above, what is the characteristic equation?
4. For each of the models listed above, what is the inverse characteristic equation?

# VII
---
7.3.1 Exercises
1. Unit root tests have notoriously low power, especially if the AR coefficient is
close to one. In this exercise, you are asked to explore this for yourself. Generate
100 observations from a stationary zero-mean AR(1) process with β = 0.95.
Draw the errors independently from an N(0,1) distribution. Conduct a dfuller
test with the noconstant option. Are you able to reject the null of a unit root?
Repeat the exercise another nine times for a total of ten experiments. In how
many instances are you able to reject the null hypothesis?
2. Repeat the exercise above but with 1000 observations and with β = 0.99. In how
many of the ten instances are you able to reject the null hypothesis? (We should
be rejecting 95% of the time, but we reject far less frequently than that.)
3. Repeat the previous exercise (N = 1000 obs and β = 0.99) but write a loop to
conduct the exercise 1000 times. What proportion of the times are you able to
reject the null hypothesis? Do you reject approximately 95% of the time? (Hint:
you can’t possibly count by hand the number of times the reported test statistic
is greater than the critical value. Set up a counter to do this.)


7.3.6 Exercises
1. Apply DF-GLS to the Nelson and Plosser (1982) dataset. Allow for a trend. Use
Ng and Perron’s modified AIC for lag selection. Use 5% for hypothesis testing.
Which of the variables are trend stationary? Which seem to be random walks
with drift?


7.5 Exercises
1. Kwiatkowski et al. (1992) applied their method to the Nelson and Plosser (1982)
dataset and came to some different conclusions. In this exercise, you will now
replicate KPSS’s study using Stata on NelsonPlosserData.dta.
(a) Calculate the KPSS test statistic for a model with no trend (notrend) and a
maximal lag of eight periods (maxlag(8)). Which variables seem to have
unit roots? (You can double-check your work by looking at Table 5a in the
original KPSS paper.)
(b) Calculate the KPSS test statistic for a model which allows for a trend (i.e.
don’t include the notrend option) and a maximal lag of eight periods
(maxlag(8)). Which variables seem to have unit roots? (You can doublecheck your work by looking at Table 5b in the original KPSS paper
2. Redo both parts of the above exercise, but with the following modifications: let
Stata pick the optimal lag length (using the auto option), and have Stata use
a quadratic kernel to estimate the long-run variance of the series (using the qs
option). Which variables seem to have unit roots?


7.6 REPLICATION

Exercises
1. Using the code provided in the text, replicate Table 7.5 containing Nelson and
Plosser’s main results.
2. Are the major stock market indexes unit root processes? Redo the Nelson and Plosser exercise, but with daily data on the NASDAQ index,
the CAC-40 index, and the DAX for the period starting in 2013 and
ending in 2017. (Use the Index.dta dataset or download the data
using fetchyahooquotes ^IXIC ^FCHI ^GDAXI, freq(d)
start(01012013) end(01012018).) What do you find?

# VIII
---
8.1 Exercises
1. Modify the code above to replicate the rest of Table 8.2.
2. Load the DJIA.dta dataset. This dataset reports the Dow Jones Industrial Average
from the beginning of 1995 to the end of 2015. (Alternatively, download the
data using fetchyahooquotes.) Take the natural log of the DJIA. Conduct
a Dickey-Fuller test on ln(DJIA). Does there seem to be a unit root in the
(log of the) DJIA? Graph the data. Visually, does there seem to be a structural
break? If so, of what type (slope change, intercept change, or both)? Estimate
the appropriate model, and conduct a unit root test following the Perron’s (1989)
procedure, as laid out in this chapter. Does there seem to be a unit root in the
DJIA once a structural break has been accounted for?


8.3.1 Replicating Zivot and Andrews


8.3.2 Exercises
1. Repeat Perron’s exercise on the Nelson and Plosser dataset, but use Stata’s
zandrews command and the AIC option to identify the existence and most
likely location of a structural break. Ignore data before 1909. For each variable,
which year is identified as the most likely for a structural break? Which of these
are statistically significant? Are your results different from those identified by
Perron? (Recall that real wages and the S&P 500 are thought to have a new
intercept and slope after the break. All other variables have only a new intercept.)
Are your results different from those in Zivot and Andrews’ paper?
2. Repeat the exercise above, but use Stata’s zandrews command and the
sequential t-test option (at the 0.10 level) to identify the existence and most
likely date of a structural break. Are your results different from those identified
by Perron? Are your results different from those in the previous exercise? Are
your results different from those in Zivot and Andrews’ paper?

# IX
---

# X
---

<style>
h1 {
  border: 1.5px solid #333;
  padding: 8px 12px;
  background-image: linear-gradient(180deg, #fff, rgb(160, 147, 147));
  position: static;
}
</style>

# XI
---

# XII
---