# Ex. 1 | **datos.gob.ar**
### GEC0319 | JIVB | Time Series

## Settings

Armar una función wrapper que facilite construir llamadas a la API.

In [1]:
import requests
import urllib.parse
import pandas as pd

def get_api_call(ids, **kwargs):
    API_BASE_URL = "https://apis.datos.gob.ar/series/api/"
    kwargs["ids"] = ",".join(ids)
    return "{}{}?{}".format(API_BASE_URL, "series", urllib.parse.urlencode(kwargs))

Una llamada válida a la API debe tener por lo menos un id de una serie válida, y luego puede tener parámetros opcionales.

In [2]:
api_call = get_api_call(["168.1_T_CAMBIOR_D_0_0_26"], start_date="2018-08")
print(api_call)

https://apis.datos.gob.ar/series/api/series?start_date=2018-08&ids=168.1_T_CAMBIOR_D_0_0_26

Obtener la respuesta en un diccionario.

In [3]:
result = requests.get(api_call).json()
print(result)

{'data': [['2018-08-01', 28.6], ['2018-08-02', 28.6], ['2018-08-03', 28.6], ['2018-08-04', 28.6], ['2018-08-05', 28.6], ['2018-08-06', 28.6], ['2018-08-07', 28.6], ['2018-08-08', 28.1], ['2018-08-09', 28.6], ['2018-08-10', 29.7], ['2018-08-11', 29.7], ['2018-08-12', 29.7], ['2018-08-13', 30.5], ['2018-08-14', 30.1], ['2018-08-15', 30.5], ['2018-08-16', 30.3], ['2018-08-17', 30.3], ['2018-08-18', 30.3], ['2018-08-19', 30.3], ['2018-08-20', 30.3], ['2018-08-21', 30.5], ['2018-08-22', 30.7], ['2018-08-23', 31.0], ['2018-08-24', 31.4], ['2018-08-25', 31.4], ['2018-08-26', 31.4], ['2018-08-27', 31.4], ['2018-08-28', 31.9], ['2018-08-29', 34.5], ['2018-08-30', 38.2], ['2018-08-31', 37.4], ['2018-09-01', 37.4], ['2018-09-02', 37.4], ['2018-09-03', 38.0], ['2018-09-04', 39.5], ['2018-09-05', 39.0], ['2018-09-06', 38.0], ['2018-09-07', 37.6], ['2018-09-08', 37.6], ['2018-09-09', 37.6], ['2018-09-10', 37.6], ['2018-09-11', 38.5], ['2018-09-12', 38.8], ['2018-09-13', 40.1], ['2018-09-14', 40.4], ['2018-09-15', 40.4], ['2018-09-16', 40.4], ['2018-09-17', 40.2], ['2018-09-18', 40.3], ['2018-09-19', 39.8], ['2018-09-20', 38.8], ['2018-09-21', 37.8], ['2018-09-22', 37.8], ['2018-09-23', 37.8], ['2018-09-24', 37.9], ['2018-09-25', 38.7], ['2018-09-26', 39.2], ['2018-09-27', 40.6], ['2018-09-28', 42.1], ['2018-09-29', 42.1], ['2018-09-30', 42.1], ['2018-10-01', 40.5], ['2018-10-02', 39.0], ['2018-10-03', 38.6], ['2018-10-04', 39.2], ['2018-10-05', 38.7], ['2018-10-06', 38.7], ['2018-10-07', 38.7], ['2018-10-08', 38.4], ['2018-10-09', 38.0], ['2018-10-10', 38.0], ['2018-10-11', 37.5], ['2018-10-12', 37.6], ['2018-10-13', 37.6], ['2018-10-14', 37.6], ['2018-10-15', 37.6], ['2018-10-16', 36.9], ['2018-10-17', 37.1], ['2018-10-18', 37.5], ['2018-10-19', 37.5], ['2018-10-20', 37.5], ['2018-10-21', 37.5], ['2018-10-22', 37.3], ['2018-10-23', 37.5], ['2018-10-24', 37.9], ['2018-10-25', 37.7], ['2018-10-26', 37.8], ['2018-10-27', 37.8], ['2018-10-28', 37.8], ['2018-10-29', 37.8], ['2018-10-30', 37.6], ['2018-10-31', 36.8], ['2018-11-01', 36.6], ['2018-11-02', 36.4], ['2018-11-03', 36.4], ['2018-11-04', 36.4], ['2018-11-05', 36.4], ['2018-11-06', 36.4], ['2018-11-07', 36.6], ['2018-11-08', 36.4]], 'count': 2088, 'meta': [{'frequency': 'day', 'start_date': '2018-08-01', 'end_date': '2018-11-08'}, {'catalog': {'title': 'Datos Programación Macroeconómica'}, 'dataset': {'title': 'Tipo de Cambio $-USD - Futuro Dólar', 'description': 'Datos de tipo de cambio $-USD - futuro dólar . Con respecto al dólar de Estados Unidos. Frecuencia diaria.', 'issued': '2017-09-28', 'source': 'BCRA, MAE, Rofex'}, 'distribution': {'title': 'Tipo de cambio $-USD - futuro dólar. Valores diarios', 'downloadURL': 'https://infra.datos.gob.ar/catalog/sspm/dataset/168/distribution/168.1/download/datos-tipo-cambio-usd-futuro-dolar-frecuencia-diaria.csv'}, 'field': {'description': 'Tipo de Cambio BNA (Vendedor)', 'id': '168.1_T_CAMBIOR_D_0_0_26', 'units': 'Pesos argentinos por dólar', 'representation_mode': 'value', 'representation_mode_units': 'Pesos argentinos por dólar'}}], 'params': {'start_date': '2018-08', 'ids': '168.1_T_CAMBIOR_D_0_0_26', 'identifiers': [{'id': '168.1_T_CAMBIOR_D_0_0_26', 'distribution': '168.1', 'dataset': '168'}]}}

In [4]:
df = pd.DataFrame(result['data'],columns=['ts','tipo_de_cambio'])
df.head()

           ts  tipo_de_cambio
0  2018-08-01            28.6
1  2018-08-02            28.6
2  2018-08-03            28.6
3  2018-08-04            28.6
4  2018-08-05            28.6

In [5]:
df_parques = pd.read_csv('visitas-residentes-y-no-residentes.csv')

In [6]:
df_parques.head(3)

  indice_tiempo origen_visitantes  visitas observaciones
0    2008-01-01     no residentes   198407           NaN
1    2008-01-01        residentes   352303           NaN
2    2008-01-01             total   550710           NaN

In [9]:
api_call = 'https://apis.datos.gob.ar/series/api/series/?ids=43.2_ECTATN_0_T_41&limit=5000&format=csv'
result = requests.get(api_call).json
print(result)

<Response [200]>

In [ ]:
import pandas as pd

df = pd.read_csv(get_api_call(
    ["168.1_T_CAMBIOR_D_0_0_26", "101.1_I2NG_2016_M_22",
    "116.3_TCRMA_0_M_36", "143.3_NO_PR_2004_A_21", "11.3_VMATC_2004_M_12"],
    format="csv", start_date=2018
))

In [18]:
api_call = get_api_call(['43.2_ECTATN_0_T_41'], start_date="2018-08")
print(api_call)
result = requests.get(api_call).json()
print(result)

https://apis.datos.gob.ar/series/api/series?start_date=2018-08&ids=43.2_ECTATN_0_T_41
{'data': [['2018-10-01', 0.441], ['2019-01-01', 0.449], ['2019-04-01', 0.483], ['2019-07-01', 0.4629999999999999], ['2019-10-01', 0.457], ['2020-01-01', 0.449], ['2020-04-01', 0.391], ['2020-07-01', 0.453], ['2020-10-01', 0.448056002147957], ['2021-01-01', 0.435], ['2021-04-01', 0.436646252270499], ['2021-07-01', 0.452], ['2021-10-01', 0.457], ['2022-01-01', 0.47], ['2022-04-01', 0.468], ['2022-07-01', 0.4479999999999999], ['2022-10-01', 0.453403366119115], ['2023-01-01', 0.490745227860609], ['2023-04-01', 0.474], ['2023-07-01', 0.479027620022091], ['2023-10-01', 0.502], ['2024-01-01', 0.509]], 'count': 22, 'meta': [{'frequency': 'quarter', 'start_date': '2018-10-01', 'end_date': '2024-01-01'}, {'catalog': {'title': 'Datos Programación Macroeconómica'}, 'dataset': {'title': 'Principales variables ocupacionales. EPH continua. Actividad', 'description': 'Tasa de actividad por aglomerados urbanos', 'issued': '2017-09-28', 'source': 'Instituto Nacional de Estadística y Censos (INDEC)'}, 'distribution': {'title': 'Tasa de actividad. Valores trimestrales', 'downloadURL': 'https://infra.datos.gob.ar/catalog/sspm/dataset/43/distribution/43.2/download/tasa-actividad-valores-trimestrales.csv'}, 'field': {'description': 'Tasa de actividad total Neuquén. En porcentaje.', 'id': '43.2_ECTATN_0_T_41', 'units': 'Porcentaje', 'representation_mode': 'value', 'representation_mode_units': 'Porcentaje'}}], 'params': {'start_date': '2018-08', 'ids': '43.2_ECTATN_0_T_41', 'identifiers': [{'id': '43.2_ECTATN_0_T_41', 'distribution': '43.2', 'dataset': '43'}]}}

In [20]:
pd.DataFrame(result['data'])

             0         1
0   2018-10-01  0.441000
1   2019-01-01  0.449000
2   2019-04-01  0.483000
3   2019-07-01  0.463000
4   2019-10-01  0.457000
5   2020-01-01  0.449000
6   2020-04-01  0.391000
7   2020-07-01  0.453000
8   2020-10-01  0.448056
9   2021-01-01  0.435000
10  2021-04-01  0.436646
11  2021-07-01  0.452000
12  2021-10-01  0.457000
13  2022-01-01  0.470000
14  2022-04-01  0.468000
15  2022-07-01  0.448000
16  2022-10-01  0.453403
17  2023-01-01  0.490745
18  2023-04-01  0.474000
19  2023-07-01  0.479028
20  2023-10-01  0.502000
21  2024-01-01  0.509000